// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_RGDi03tdqFFzba934JoEK6Uqodr2llk',
    appId: '1:419251176337:android:ddfef58f79163c0b651030',
    messagingSenderId: '419251176337',
    projectId: 'myproject-9638b',
    databaseURL: 'https://myproject-9638b-default-rtdb.firebaseio.com',
    storageBucket: 'myproject-9638b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWTf-XisM5TX8YbDgHu-O22oPn8BSQXMM',
    appId: '1:419251176337:ios:c36a915ab66446c0651030',
    messagingSenderId: '419251176337',
    projectId: 'myproject-9638b',
    databaseURL: 'https://myproject-9638b-default-rtdb.firebaseio.com',
    storageBucket: 'myproject-9638b.appspot.com',
    androidClientId: '419251176337-7j14o111bd00b6sk0qh9g9dlp48mvskt.apps.googleusercontent.com',
    iosClientId: '419251176337-i1s6s20o36eacloroitpchqf7h1tjjhl.apps.googleusercontent.com',
    iosBundleId: 'com.example.qiuInternar',
  );
}
